### ISSUE TITLE
在不修改源码的情况下配置文件是否需要新建文件夹

### ISSUE THREAD

**Issue by RAINighty** [summerkirakira/biliRecorder#1]
readme上写“配置文件在config/config.json中”，但是您上传的文件里并没有config文件夹，那我需要新建config文件夹然后新建config.json文件吗

**Comment by RAINighty** [comment]
啊这个问题没事了，还有个问题，config.json中的cookies应该如何填写呢，前面的不都是cookie内容了吗

**Comment by summerkirakira** [comment]
直接保留null就行了

**Comment by RAINighty** [comment]
> 直接保留null就行了

谢谢，还有一个问题，"download_type": 1,"custom_downloader": null分别代表的是什么呢，因为我的机子是海外的，如果和下载线路有关系的话我可能还需要改

**Comment by summerkirakira** [comment]
这个还没有实现，保留就可以（

**Comment by RAINighty** [comment]
> 这个还没有实现，保留就可以（

哦好的感谢
