### ISSUE TITLE
运行app.py时出现提示

### ISSUE THREAD

**Issue by RAINighty** [summerkirakira/biliRecorder#2]
2022-10-10 15:58:58.805 | INFO     | services.live:start_monitor:328 - 正在监听>直播间: 31494
/root/storage/biliRecorder/app.py:7: DeprecationWarning: There is no current event loop
  asyncio.get_event_loop().run_forever()

下面的那一段是否是报错

**Comment by summerkirakira** [comment]
在3.10下可以正常使用，不会有影响的

**Comment by RAINighty** [comment]
> 在3.10下可以正常使用，不会有影响的

好的，感谢
